services:
  chatbot:
    image: chatchipmunk-api:latest
    expose:
      - "8000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - PYTHONUNBUFFERED=1
    networks:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - chatbot
    networks:
      - web

networks:
  web:
    driver: bridge
